### ISSUE TITLE
Add a reference to Radiuss-Shared-CI

### ISSUE THREAD

**Issue by adrienbernede** [rse-ops/ci#11]
## Add Reference to:

RADIUSS developed a shared GitLab CI implementation that lets you get started very quickly and coherently with other projects.

### Intended primarily to:
Open-source RADIUSS projects hosted on GitHub and willing to run extra CI on LC GitLab.

### Prerequisites
- support of Spack packaging.
- CMake build system (strongly recommended, but not mandatory).

### Documentation
https://radiuss-shared-ci.readthedocs.io/en/latest/

### Sources
https://github.com/LLNL/radiuss-shared-ci

**Comment by vsoch** [comment]
@adrienbernede for your review! https://github.com/rse-ops/ci/pull/13
