### ISSUE TITLE
Add reference to MFEM Github Actions

### ISSUE THREAD

**Issue by adrienbernede** [rse-ops/ci#12]
## Add reference to

RADIUSS developed a set of Github Actions to install MFEM dependencies and MFEM itself in the Github Actions context.

### Primarily intended to

Open-source projects hosted on Github and willing to install the already supported projects or contribute new projects to the repo (we could extend that to other math projects to build a coherent set of actions).

### Sources

https://github.com/mfem/github-actions

### Notes

Not building any containers, builds dependencies on top of classic runners images. See MFEM/mfem actions for usage example.

**Comment by vsoch** [comment]
Great idea!
